name-template: "asMSX v.$NEXT_PATCH_VERSION"
tag-template: "$NEXT_PATCH_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"
change-template: "* #$NUMBER - $TITLE , thanks to @$AUTHOR!"
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bugs killed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

template: |
  ## Changelog
  $CHANGES
