name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'ref/**'
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'ref/**'
      - '*.md'

jobs:
  windows:
    name: windows ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: i686
            bits: "32"
          - target: x86-64
            bits: "64"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: |
        sudo apt update
        sudo apt install -y libbison-dev libfl-dev build-essential cmake flex bison libpthread-stubs0-dev libgtest-dev
        sudo apt install -y gcc-mingw-w64-${{ matrix.target }} g++-mingw-w64-${{ matrix.target }}
    - name: make
      run: make asmsx${{ matrix.bits }}.exe
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: asmsx-win-${{ matrix.target }}
        path: asmsx*.exe

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: |
        sudo apt update
        sudo apt install -y libbison-dev libfl-dev build-essential cmake flex bison libpthread-stubs0-dev libgtest-dev
    - name: make
      run: make
    - name: test
      run: make test
    - name: cleanup and build again
      run: |
        make clean
        make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: asmsx-linux-x86_64
        path: asmsx

  linux-armhf:
    needs: linux
    runs-on: ubuntu-latest
    env:
      GCC_VERSION: "10.2-2020.11"
      BUILD_TARGET: arm-none-linux-gnueabihf
      GCC_NAME: "gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: |
        sudo apt update
        sudo apt install -y libbison-dev libfl-dev build-essential cmake flex bison libpthread-stubs0-dev libgtest-dev
        wget https://developer.arm.com/-/media/Files/downloads/gnu-a/${{ env.GCC_VERSION }}/binrel/${{ env.GCC_NAME }}.tar.xz
        tar xvf ${{ env.GCC_NAME }}.tar.xz
    - name: make
      run: make CC=${{ env.GCC_NAME }}/bin/${{ env.BUILD_TARGET }}-gcc LDFLAGS="-static"
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: asmsx-${{ env.BUILD_TARGET }}
        path: asmsx

  osx:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: brew install flex bison
    - name: make
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: asmsx-osx
        path: asmsx

