name: Build

on:
  push:
    branches: [ master ]
    tags:
      - "*.*.*"
    paths-ignore:
      - 'doc/**'
      - 'ref/**'
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
      - 'ref/**'
      - '*.md'

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
    - name: install deps
      run: |
        nuget restore build/vs2019/asmsx.sln
        nuget install build/vs2019/asmsx-gtest/packages.config -OutputDirectory build/vs2019/asmsx-gtest/packages
        choco install winflexbison
    - name: make
      run: msbuild build/vs2019/asmsx.sln
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: asmsx-win-x86_64
        path: build/vs2019/Debug/asmsx.exe

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: |
        sudo apt update
        sudo apt install -y libbison-dev libfl-dev build-essential cmake flex bison libpthread-stubs0-dev libgtest-dev
    - name: make
      run: make
    - name: test
      run: make test
    - name: cleanup and build again
      run: |
        make clean
        make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: asmsx-linux-x86_64
        path: asmsx

  linux-armhf:
    needs: linux
    runs-on: ubuntu-latest
    env:
      GCC_VERSION: "10.2-2020.11"
      BUILD_TARGET: arm-none-linux-gnueabihf
      GCC_NAME: "gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: |
        sudo apt update
        sudo apt install -y libbison-dev libfl-dev build-essential cmake flex bison libpthread-stubs0-dev libgtest-dev
        wget https://developer.arm.com/-/media/Files/downloads/gnu-a/${{ env.GCC_VERSION }}/binrel/${{ env.GCC_NAME }}.tar.xz
        tar xvf ${{ env.GCC_NAME }}.tar.xz
    - name: make
      run: make CC=${{ env.GCC_NAME }}/bin/${{ env.BUILD_TARGET }}-gcc LDFLAGS="-static"
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: asmsx-${{ env.BUILD_TARGET }}
        path: asmsx

  osx:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: brew install flex bison
    - name: make
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: asmsx-osx
        path: asmsx

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [windows, linux, linux-armhf, osx]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: assets
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: false
        files: |
          assets/*

